### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by madhavsuresh** [smcql/smcql#1]
$ ./setup.sh
$ ./build_and_execute.sh conf/workload/sql/cdiff.sql testDB1 testDB2
Creating executable...
Executing Query...

Query:
WITH diags (patient_id, timestamp_, r) AS (
 SELECT patient_id,timestamp_, row_number()  OVER (PARTITION BY patient_id ORDER BY timestamp_) AS r
 FROM cdiff_cohort_diagnoses
 WHERE icd9 = '008.45')
SELECT DISTINCT d1.patient_id
       FROM diags d1 JOIN diags d2 ON d1.patient_id = d2.patient_id
       WHERE TIMESTAMPDIFF(DAY, d2.timestamp_, d1.timestamp_) >=  15 AND TIMESTAMPDIFF(DAY, d2.timestamp_, d1.timestamp_) <= 56  AND d1.r+1 = d2.r
[testDB2] java.lang.IllegalArgumentException
[testDB2] 	at com.oblivm.backend.util.Utils.log2(Utils.java:330)
[testDB2] 	at com.oblivm.backend.util.Utils.log2Ceil(Utils.java:336)
[testDB2] 	at com.oblivm.backend.oram.LinearScanOram.<init>(LinearScanOram.java:29)
[testDB2] 	at com.oblivm.backend.oram.SecureArray.<init>(SecureArray.java:44)
[testDB2] 	at org.smcql.generated.userQuery.WindowAggregate3.NoClass.run(NoClass.java:110)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:197)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.secureCompute(SMCQLRunnableImpl.java:101)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnable$Evaluator.secureCompute(SMCQLRunnable.java:256)
[testDB2] 	at com.oblivm.backend.util.EvaRunnable.runCore(EvaRunnable.java:57)
[testDB2] 	at com.oblivm.backend.util.EvaRunnable.run(EvaRunnable.java:78)
[testDB2] 	at java.lang.Thread.run(Thread.java:748)
[testDB1] java.lang.IllegalArgumentException
[testDB1] 	at com.oblivm.backend.util.Utils.log2(Utils.java:330)
[testDB1] 	at com.oblivm.backend.util.Utils.log2Ceil(Utils.java:336)
[testDB1] 	at com.oblivm.backend.oram.LinearScanOram.<init>(LinearScanOram.java:29)
[testDB1] 	at com.oblivm.backend.oram.SecureArray.<init>(SecureArray.java:44)
[testDB1] 	at org.smcql.generated.userQuery.WindowAggregate3.NoClass.run(NoClass.java:110)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:197)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.secureCompute(SMCQLRunnableImpl.java:101)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnable$Generator.secureCompute(SMCQLRunnable.java:83)
[testDB1] 	at com.oblivm.backend.util.GenRunnable.runCore(GenRunnable.java:54)
[testDB1] 	at com.oblivm.backend.util.GenRunnable.run(GenRunnable.java:77)
[testDB1] 	at java.lang.Thread.run(Thread.java:748)

**Comment by jennierogers** [comment]
@madhavsuresh  would you please commit this fix so we can close this issue?

**Comment by madhavsuresh** [comment]
Looks like it was merged with this PR https://github.com/smcql/smcql/pull/2
